import { StyleSheet } from 'react-native';
import colors from '../../theme/colors';
import fonts from '../../theme/fonts';

const OrderDetailsScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: fonts.size.lg,
    fontFamily: fonts.family.medium,
    color: colors.textPrimary,
  },
  shareButton: {
    padding: 8,
  },
  scrollView: {
    flex: 1,
    backgroundColor: colors.bgOffWhiteSecondary,
  },
  statusCard: {
    backgroundColor: '#fff',
    margin: 12,
    // padding: 16,
    paddingBottom: 16,
    borderRadius: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    overflow: 'hidden',
  },
  statusHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 4,
    // borderRadius: 20,
    borderBottomRightRadius: 8,
  },
  statusText: {
    color: '#FFF',
    fontSize: fonts.size.sm,
    fontFamily: fonts.family.medium,
    marginLeft: 4,
  },
  estimatedTime: {
    fontSize: fonts.size.md,
    fontFamily: fonts.family.semibold,
    color: colors.textPrimary,
    marginRight: 10,
    paddingTop: 4,
    // borderWidth:0.6
  },
  trackerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingHorizontal: 8,
    marginBottom: 8,
    // borderWidth:0.7
  },
  trackerStep: {
    flex: 1,
    alignItems: 'center',
  },
  trackerDot: {
    width: 20,
    height: 20,
    borderRadius: 12,
    backgroundColor: '#e0e0e0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  trackerDotActive: {
    backgroundColor: colors.brandPrimary,
  },
  trackerLine: {
    position: 'absolute',
    top: 10,
    left: '50%',
    width: '100%',
    height: 2,
    backgroundColor: '#e0e0e0',
    zIndex: -1,
    
  },
  trackerLineActive: {
    backgroundColor: colors.brandPrimary,
  },
  fullLine: {
  position: 'absolute',
  top: 10,
  left: 0,
  right: 0,
  height: 2,
  backgroundColor: '#e0e0e0',
  zIndex: -1,
},

activeLine: {
  position: 'absolute',
  top: 10,
  left: 0,
  height: 2,
  backgroundColor: colors.brandPrimary,
  zIndex: -1,
},

  trackerLabelsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    // borderWidth:0.7
  },
  trackerText: {
    fontSize: fonts.size.xs,
    fontFamily: fonts.family.regular,
    color: '#6d6d6d',
    textAlign: 'center',
    flex: 1,
  },
  trackerTextActive: {
    color: colors.brandPrimary,
    fontFamily: fonts.family.semibold,
  },
  mapCard: {
    backgroundColor: '#fff',
    marginHorizontal: 12,
    marginBottom: 12,
    borderRadius: 12,
    overflow: 'hidden',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  mapPlaceholder: {
    height: 150,
    backgroundColor: '#f0f0f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapText: {
    fontSize: 16,
    fontFamily: fonts.family.semibold,
    color: colors.textPrimary,
    marginTop: 8,
  },
  mapSubText: {
    fontSize: 14,
    color: '#666',
    marginTop: 4,
  },
  deliveryPartnerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  deliveryPartnerPhoto: {
    width: 48,
    height: 48,
    borderRadius: 24,
  },
  deliveryPartnerInfo: {
    flex: 1,
    marginLeft: 12,
  },
  deliveryPartnerName: {
    fontSize: 16,
    fontFamily: fonts.family.semibold,
    color: colors.textPrimary,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ratingText: {
    fontSize: 14,
    color: '#666',
    marginLeft: 4,
  },
  deliveryPartnerActions: {
    flexDirection: 'row',
  },
  actionIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f0f0f0',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  card: {
    backgroundColor: '#fff',
    marginHorizontal: 12,
    marginBottom: 12,
    padding: 16,
    borderRadius: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  restaurantHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  restaurantImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
  },
  restaurantInfo: {
    flex: 1,
    marginLeft: 12,
  },
  restaurantName: {
    fontSize: fonts.size.md,
    fontFamily: fonts.family.medium,
    color: colors.textPrimary,
  },
  orderId: {
    fontSize: fonts.size.md,
    fontFamily: fonts.family.regular,
    color: '#666',
    marginTop: 4,
  },
  orderMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  orderMetaText: {
    fontSize: fonts.size.md,
    fontFamily: fonts.family.regular,
    color: '#666',
  },
  sectionTitle: {
    fontSize: fonts.size.md,
    fontFamily: fonts.family.medium,
    color: colors.textPrimary,
    marginBottom: 12,
  },
  itemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
  },
  itemRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  itemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  itemTypeIcon: {
    width: 14,
    height: 14,
    marginRight:5
  },
  vegIndicator: {
    width: 20,
    height: 20,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  vegDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#32CD32',
  },
  itemName: {
    fontSize: fonts.size.md,
    fontFamily: fonts.family.regular,
    color: colors.textPrimary,
    flex: 1,
  },
  itemRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  itemQuantity: {
    fontSize: 14,
    color: '#666',
    marginRight: 16,
  },
  itemPrice: {
    fontSize: 14,
    fontFamily: fonts.family.semibold,
    color: colors.textPrimary,
    minWidth: 60,
    textAlign: 'right',
  },
  specialInstructions: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fffbe6',
    padding: 12,
    borderRadius: 8,
    marginTop: 8,
  },
  instructionsText: {
    fontSize: fonts.size.md,
    fontFamily: fonts.family.regular,
    color: '#666',
    marginLeft: 8,
    flex: 1,
    fontStyle: 'italic',
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
  },
  priceLabel: {
    fontSize: fonts.size.md,
    fontFamily: fonts.family.regular,
    color: '#666',
  },
  priceValue: {
    fontSize: fonts.size.md,
    fontFamily: fonts.family.regular,
    color: colors.textPrimary,
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: '#eee',
    marginTop: 6,
    paddingTop: 12,
  },
  totalLabel: {
    fontSize: fonts.size.md,
    fontFamily: fonts.family.semibold,
    color: colors.textPrimary,
  },
  totalValue: {
    fontSize: fonts.size.md,
    fontFamily: fonts.family.semibold,
    color: colors.textPrimary,
  },
  addressContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  addressTextContainer: {
    flex: 1,
    marginLeft: 12,
  },
  addressLabel: {
    fontSize: fonts.size.md,
    fontFamily: fonts.family.semibold,
    color: colors.textPrimary,
  },
  addressText: {
    fontSize: fonts.size.sm,
    fontFamily: fonts.family.regular,
    color: '#666',
    marginTop: 4,
    lineHeight: 20,
  },
  paymentContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  paymentLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  paymentTextContainer: {
    marginLeft: 12,
  },
  paymentMethod: {
    fontSize: fonts.size.md,
    fontFamily: fonts.family.semibold,
    color: colors.textPrimary,
  },
  paymentStatus: {
    fontSize: fonts.size.sm,
    fontFamily: fonts.family.medium,
    color: '#32CD32',
    marginTop: 2,
  },
  paymentAmount: {
    fontSize: fonts.size.md,
    fontFamily: fonts.family.bold,
    color: colors.textPrimary,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
  },
  infoLabel: {
    fontSize: fonts.size.sm,
    fontFamily: fonts.family.regular,
    color: '#666',
  },
  infoValue: {
    fontSize: fonts.size.sm,
    color: colors.textPrimary,
    fontFamily: fonts.family.regular,
  },
  ratingSectionContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 12,
  },
  ratingStar: {
    padding: 8,
  },
  ratingThankYou: {
    textAlign: 'center',
    fontSize: fonts.size.sm,
    color: '#32CD32',
    fontFamily: fonts.family.regular,
    marginTop: 8,
  },
  tipContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 12,
  },
  tipButton: {
    paddingHorizontal: 24,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.brandPrimary,
  },
  tipButtonActive: {
    backgroundColor: colors.brandPrimary,
  },
  tipButtonText: {
    fontSize: fonts.size.md,
    fontFamily: fonts.family.semibold,
    color: colors.brandPrimary,
  },
  tipButtonTextActive: {
    color: '#FFF',
  },
  tipThankYou: {
    textAlign: 'center',
    fontSize: 14,
    color: '#32CD32',
    fontFamily: fonts.family.semibold,
    marginTop: 8,
  },
  actionButtonsContainer: {
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  downloadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.brandPrimary,
    marginBottom: 12,
  },
  downloadButtonText: {
    fontSize: 16,
    fontFamily: fonts.family.semibold,
    color: colors.brandPrimary,
    marginLeft: 8,
  },
  reorderButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.brandPrimary,
    padding: 14,
    borderRadius: 12,
  },
  reorderButtonText: {
    fontSize: 16,
    fontFamily: fonts.family.semibold,
    color: '#FFF',
    marginLeft: 8,
  },
  helpSection: {
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  helpButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    // backgroundColor: '#fff',
    padding: 14,
    borderRadius: 12,
  },
  helpButtonText: {
    fontSize: 14,
    color: colors.brandPrimary,
    marginLeft: 8,
    fontFamily: fonts.family.medium,
  },
  bottomPadding: {
    height: 20,
  },
  // Pay Now Button Styles
  payNowButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.brandPrimary,
    padding: 14,
    borderRadius: 12,
    marginTop: 12,
  },
  payNowButtonText: {
    fontSize: 16,
    fontFamily: fonts.family.semibold,
    color: '#FFF',
    marginLeft: 8,
  },
  // Payment Options Styles
  paymentOptionsContainer: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  paymentOptionsTitle: {
    fontSize: fonts.size.sm,
    fontFamily: fonts.family.medium,
    color: '#666',
    marginBottom: 12,
  },
  paymentOptionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  paymentOptionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.brandPrimary,
    marginHorizontal: 4,
  },
  paymentOptionButtonSelected: {
    backgroundColor: colors.brandPrimary,
  },
  paymentOptionText: {
    fontSize: fonts.size.sm,
    fontFamily: fonts.family.medium,
    color: colors.brandPrimary,
    marginLeft: 6,
  },
  paymentOptionTextSelected: {
    color: '#FFF',
  },
});

export default OrderDetailsScreenStyles;
